name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      valkey:
        image: valkey/valkey:7.2-alpine
        ports:
          - 6379: 6379
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Verify Valkey connection
        run: |
          timeout 30 bash -c 'until valkey-cli -h localhost -p 6379 ping; do sleep 1; done'
          echo "Valkey ready"

      - name: Print Zig Version
        run: zig version

      - name: Build
        run: zig build --verbose

      - name: Run Tests
        run: |
          zig build test --summary all
        env:
          VALKEY_HOST: 127.0.0.1
          VALKEY_PORT: 6379
