name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      
      - name: Build nix
        run: |
          nix-build
          nix-shell -p valkey
        if: matrix.platform != windows-latest

      - name: Print Zig Version
        run: zig version

      - name: Build
        run: zig build --verbose

      - name: Run Tests
        run: |
          valkey-server --daemonize yes && zig build test --summary all
